version: 2.1

defaults: &defaults
  working_directory: ~/truemail-java-client
  docker:
    - image: cimg/openjdk:8.0-browsers
  environment:
    RULESET: pmd-ruleset.xml

jobs:
  linters:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - pmd-v6.27.0
      - run:
          name: Install PMD
          command: |
              if [ ! -d pmd-bin-6.27.0 ]; then
                  curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases/6.27.0/pmd-bin-6.27.0.zip" -o pmd-bin-6.27.0.zip
                  unzip pmd-bin-6.27.0.zip
                  rm pmd-bin-6.27.0.zip
              fi
      - save_cache:
          paths:
              - pmd-bin-6.27.0
          key: pmd-v6.27.0
      - run:
          name: Run Static Analysis
          command: |
              pmd-bin-6.27.0/bin/run.sh pmd -d . -R $RULESET -f text -l apex -r linters.txt
      - store_artifacts:
          path: linters.txt

  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Build project
          command: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ./
          paths:
            - target/

  tests:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run:
          name: Run tests
          command: mvn test

workflows:
  build:
    jobs:
      - linters
      - build
      - tests:
          requires:
            - build
